const { chromium } = require("playwright");
const fs = require("fs");

// Load baseline
const baseline = JSON.parse(
  fs.readFileSync("tests/dom-analysis/baseline.json", "utf8"),
);

// Regression variants
const variants = [
  "color-bug",
  "subtle-color-bug",
  "layout-bug",
  "visibility-bug",
  "typography-bug",
  "spacing-bug",
  "alignment-bug",
  "overflow-bug",
  "theme-bug",
];

// Create results folder
fs.mkdirSync("tests/dom-analysis/results", {
  recursive: true,
});

const allResults = [];

(async () => {
  const browser = await chromium.launch({
    headless: true,
  });

  for (const variant of variants) {
    const page = await browser.newPage({
      viewport: {
        width: 1440,
        height: 900,
      },
    });

    await page.goto(`http://localhost:3000/index.html?variant=${variant}`);

    // Capture current layout
    const current = await page.evaluate(() => {
      const elements = {};

      document
        .querySelectorAll(".sidebar, .topbar, .stat-card, .primary-btn, table")
        .forEach((el, index) => {
          const rect = el.getBoundingClientRect();

          elements[index] = {
            tag: el.tagName,

            x: rect.x,
            y: rect.y,

            width: rect.width,
            height: rect.height,

            visible:
              rect.width > 0 &&
              rect.height > 0 &&
              getComputedStyle(el).display !== "none",
          };
        });

      return elements;
    });

    let positionChanges = 0;
    let sizeChanges = 0;
    let visibilityChanges = 0;

    const details = [];

    console.log("\n==================================");
    console.log(`Checking ${variant}`);
    console.log("==================================");

    for (const id in baseline) {
      const b = baseline[id];
      const c = current[id];

      if (!c) {
        visibilityChanges++;

        details.push(`Element ${id} (${b.tag}) is missing`);

        console.log(`❌ Element ${id} missing`);

        continue;
      }

      // Position

      if (Math.abs(b.x - c.x) > 5 || Math.abs(b.y - c.y) > 5) {
        positionChanges++;

        details.push(`${b.tag} (Element ${id}) changed position`);

        console.log(`📍 Position changed (${id})`);
      }

      // Size

      if (
        Math.abs(b.width - c.width) > 5 ||
        Math.abs(b.height - c.height) > 5
      ) {
        sizeChanges++;

        details.push(`${b.tag} (Element ${id}) changed size`);

        console.log(`📐 Size changed (${id})`);
      }

      // Visibility

      if (b.visible !== c.visible) {
        visibilityChanges++;

        details.push(`${b.tag} (Element ${id}) visibility changed`);

        console.log(`👁 Visibility changed (${id})`);
      }
    }

    const totalChanges = positionChanges + sizeChanges + visibilityChanges;

    if (totalChanges === 0) {
      console.log("✅ No structural changes detected.");
    }

    const result = {
      variant,

      totalChanges,

      positionChanges,

      sizeChanges,

      visibilityChanges,

      details,
    };

    allResults.push(result);

    await page.close();
  }

  await browser.close();

  // Save all results

  fs.writeFileSync(
    "tests/dom-analysis/results/index.json",

    JSON.stringify(allResults, null, 2),
  );

  const reportHTML = `
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">

<title>DOM Analysis Report</title>

<style>

body{
    font-family:Arial,Helvetica,sans-serif;
    background:#f4f4f4;
    margin:40px;
}

.container{
    max-width:1100px;
    margin:auto;
    background:white;
    padding:30px;
    border-radius:8px;
    box-shadow:0 0 10px rgba(0,0,0,.15);
}

h1{
    text-align:center;
    color:#2c3e50;
}

table{
    width:100%;
    border-collapse:collapse;
    margin-top:20px;
}

th{
    background:#2c3e50;
    color:white;
}

th,td{
    border:1px solid #ddd;
    padding:12px;
    text-align:center;
}

tr:nth-child(even){
    background:#f7f7f7;
}

.pass{
    color:green;
    font-weight:bold;
}

.fail{
    color:red;
    font-weight:bold;
}

.details{
    margin-top:40px;
}

ul{
    line-height:1.8;
}

</style>

</head>

<body>

<div class="container">

<h1>DOM/Layout Analysis Report</h1>

<p>

This report was automatically generated by the custom
DOM/Layout Analysis tool.

</p>

<table>

<thead>

<tr>

<th>Variant</th>
<th>Position</th>
<th>Size</th>
<th>Visibility</th>
<th>Status</th>

</tr>

</thead>

<tbody id="summary">

</tbody>

</table>

<div id="details" class="details">

</div>

</div>

<script>

fetch("results/index.json")

.then(r=>r.json())

.then(data=>{

const table=document.getElementById("summary");

const details=document.getElementById("details");

data.forEach(result=>{

table.innerHTML+=\`

<tr>

<td>\${result.variant}</td>

<td>\${result.positionChanges}</td>

<td>\${result.sizeChanges}</td>

<td>\${result.visibilityChanges}</td>

<td class="\${result.totalChanges>0?'fail':'pass'}">

\${result.totalChanges>0?'FAIL':'PASS'}

</td>

</tr>

\`;

details.innerHTML+=\`

<h2>\${result.variant}</h2>

<ul>

\${
result.details.length
?
result.details.map(item=>\`<li>\${item}</li>\`).join("")
:
"<li>No structural changes detected.</li>"
}

</ul>

<hr>

\`;

});

});

</script>

</body>

</html>
`;

  fs.writeFileSync("tests/dom-analysis/report.html", reportHTML);

  console.log("HTML report generated.");
  console.log("Open:");
  console.log("http://localhost:3000/tests/dom-analysis/report.html");
  console.log("\n==================================");
  console.log("DOM Analysis Complete");
  console.log("==================================");

  console.table(
    allResults.map((r) => ({
      Variant: r.variant,

      Position: r.positionChanges,

      Size: r.sizeChanges,

      Visibility: r.visibilityChanges,

      Status: r.totalChanges > 0 ? "FAIL" : "PASS",
    })),
  );

  console.log("\nResults saved to:");
  console.log("tests/dom-analysis/results/index.json");
})();
